name: Build, Test, and Virtual Deploy MY_PROJECT

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU for ARM emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for ARM
        run: docker buildx build --platform linux/arm/v7 -t karimamahgoune123/myprojectcicd .

      - name: Push Docker image for ARM
        run: ddocker push karimamahgoune123/myprojectcicd:latest

      - name: Verify my_project_arm.bin presence
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd ls -l my_project_arm.bin

      - name: Verify my_project_arm.bin file type
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd file my_project_arm.bin

      - name: Emulate my_project_arm.bin with QEMU for ARM
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd qemu-arm -L /usr/arm-linux-gnueabi ./my_project_arm.bin

      - name: Upload my_project_arm.bin as artifact
        uses: actions/upload-artifact@v3
        with:
          name: my_project_arm.bin
          path: /usr/src/myapp/my_project_arm.bin