name: Build, Test, and Virtual Deploy MY_PROJECT

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU for x86_64 emulation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx for x86_64 architecture
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image for x86_64
        run: docker buildx build --platform linux/amd64 -t karimamahgoune123/myprojectcicd --load .

      - name: Verify Docker image exists
        run: docker image inspect karimamahgoune123/myprojectcicd:latest

      - name: Push Docker image for x86_64
        if: success() # Push only if the build was successful
        run: docker push karimamahgoune123/myprojectcicd:latest

      - name: Run make
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd make

      - name: Run tests
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd make test

      - name: Verify my_project.bin presence
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd ls -l my_project.bin

      - name: Verify my_project.bin file type
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd file my_project.bin

      - name: Emulate my_project.bin with QEMU for x86_64
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd qemu-x86_64 ./my_project.bin

      - name: List files
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp karimamahgoune123/myprojectcicd ls -l

      - name: Deploy to server
        if: success()
        run: ssh user@server "docker pull karimamahgoune123/myprojectcicd:latest && docker run -d karimamahgoune123/myprojectcicd:latest"