name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: |
        docker build -t karimamahgoune123/myprojectcicd .

    - name: Run QEMU
      run: |
        docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -v "C:/Users/HP/qemu:/qemu" -w /usr/src/myapp karimamahgoune123/myprojectcicd /usr/src/myapp/qemu/qemu-system-arm.exe -M versatilepb -kernel my_project.bin -nographic -serial mon:stdio -display none
