name: Build and Test MY_PROJECT

on:
  push:
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t myprojectcicd .

      - name: Run make
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp myprojectcicd make

      - name: Run tests
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp myprojectcicd make test

      - name: List files
        run: docker run --rm -v ${{ github.workspace }}:/usr/src/myapp -w /usr/src/myapp myprojectcicd ls -l

      - name: Upload myprojectcicd.bin as artifact
        uses: actions/upload-artifact@v3
        with:
          name: myprojectcicd.bin
          path: myprojectcicd.bin